export const mockCryptoEvents =[
      { name: "Bitcoin", symbol: "BTC", price: 43250, change: 2.5 },
      { name: "Ethereum", symbol: "ETH", price: 2650, change: -1.2 },
      { name: "Binance Coin", symbol: "BNB", price: 315, change: 3.8 },
      { name: "Solana", symbol: "SOL", price: 98, change: 5.2 },
      { name: "XRP", symbol: "XRP", price: 0.52, change: -2.1 },
      { name: "Cardano", symbol: "ADA", price: 0.48, change: 1.8 },
      { name: "Avalanche", symbol: "AVAX", price: 36, change: 4.5 },
      { name: "Dogecoin", symbol: "DOGE", price: 0.08, change: -0.5 },
      { name: "Polygon", symbol: "MATIC", price: 0.85, change: 2.3 },
      { name: "Chainlink", symbol: "LINK", price: 14.5, change: 1.9 },
      { name: "Litecoin", symbol: "LTC", price: 72, change: -1.8 },
      { name: "Uniswap", symbol: "UNI", price: 6.2, change: 3.1 },
      { name: "Internet Computer", symbol: "ICP", price: 12.8, change: 0.7 },
      { name: "Stellar", symbol: "XLM", price: 0.11, change: -0.9 },
      { name: "VeChain", symbol: "VET", price: 0.025, change: 2.8 },
      { name: "Filecoin", symbol: "FIL", price: 5.4, change: 1.2 },
      { name: "TRON", symbol: "TRX", price: 0.105, change: -1.5 },
      { name: "Cosmos", symbol: "ATOM", price: 9.8, change: 3.7 },
      { name: "Monero", symbol: "XMR", price: 158, change: 0.8 },
      { name: "Algorand", symbol: "ALGO", price: 0.18, change: 2.1 },
    ]