export const mockFallBackSports = [
      // NFL Events (15 events)
      {
        id: "fallback-nfl-1",
        title: "Kansas City Chiefs vs Buffalo Bills",
        description: "NFL Championship Game",
        startTime: new Date(Date.now() + 2 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 5 * 60 * 60 * 1000),
        category: "football",
        status: "upcoming",
        currentScore: null,
        markets: [
          {
            id: "fallback-nfl-1-winner",
            name: "Match Winner",
            outcomes: [
              { id: "chiefs-win", name: "Kansas City Chiefs", odds: 1.85, impliedProbability: 54.1 },
              { id: "bills-win", name: "Buffalo Bills", odds: 1.95, impliedProbability: 51.3 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 750000,
        participantCount: 1250,
      },
      {
        id: "fallback-nfl-2",
        title: "San Francisco 49ers vs Dallas Cowboys",
        description: "NFL Wild Card",
        startTime: new Date(Date.now() + 15 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 18 * 60 * 60 * 1000),
        category: "football",
        status: "upcoming",
        currentScore: null,
        markets: [
          {
            id: "fallback-nfl-2-winner",
            name: "Match Winner",
            outcomes: [
              { id: "49ers-win", name: "San Francisco 49ers", odds: 1.75, impliedProbability: 57.1 },
              { id: "cowboys-win", name: "Dallas Cowboys", odds: 2.05, impliedProbability: 48.8 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 650000,
        participantCount: 980,
      },
      {
        id: "fallback-nfl-3",
        title: "Green Bay Packers vs Minnesota Vikings",
        description: "NFL Division Championship",
        startTime: new Date(Date.now() + 4 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 7 * 60 * 60 * 1000),
        category: "football",
        status: "upcoming",
        currentScore: null,
        markets: [
          {
            id: "fallback-nfl-3-winner",
            name: "Match Winner",
            outcomes: [
              { id: "packers-win", name: "Green Bay Packers", odds: 1.9, impliedProbability: 52.6 },
              { id: "vikings-win", name: "Minnesota Vikings", odds: 1.9, impliedProbability: 52.6 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 580000,
        participantCount: 1100,
      },
      {
        id: "fallback-nfl-4",
        title: "Miami Dolphins vs New York Jets",
        description: "NFL Regular Season",
        startTime: new Date(Date.now() + 6 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 9 * 60 * 60 * 1000),
        category: "football",
        status: "upcoming",
        currentScore: null,
        markets: [
          {
            id: "fallback-nfl-4-winner",
            name: "Match Winner",
            outcomes: [
              { id: "dolphins-win", name: "Miami Dolphins", odds: 1.8, impliedProbability: 55.6 },
              { id: "jets-win", name: "New York Jets", odds: 2.0, impliedProbability: 50.0 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 420000,
        participantCount: 850,
      },
      {
        id: "fallback-nfl-5",
        title: "Pittsburgh Steelers vs Baltimore Ravens",
        description: "NFL Division Rivalry",
        startTime: new Date(Date.now() + 8 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 11 * 60 * 60 * 1000),
        category: "football",
        status: "upcoming",
        currentScore: null,
        markets: [
          {
            id: "fallback-nfl-5-winner",
            name: "Match Winner",
            outcomes: [
              { id: "steelers-win", name: "Pittsburgh Steelers", odds: 2.1, impliedProbability: 47.6 },
              { id: "ravens-win", name: "Baltimore Ravens", odds: 1.75, impliedProbability: 57.1 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 690000,
        participantCount: 1300,
      },
      // Soccer/Football Events (20 events)
      {
        id: "fallback-laliga-1",
        title: "Real Madrid vs Barcelona",
        description: "La Liga - El Clasico",
        startTime: new Date(Date.now() + 3 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 5 * 60 * 60 * 1000),
        category: "football",
        status: "upcoming",
        currentScore: null,
        markets: [
          {
            id: "fallback-laliga-1-winner",
            name: "Match Winner",
            outcomes: [
              { id: "real-win", name: "Real Madrid", odds: 2.1, impliedProbability: 47.6 },
              { id: "barca-win", name: "Barcelona", odds: 2.3, impliedProbability: 43.5 },
              { id: "draw", name: "Draw", odds: 3.2, impliedProbability: 31.3 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 950000,
        participantCount: 2100,
      },
      {
        id: "fallback-epl-1",
        title: "Manchester United vs Liverpool",
        description: "Premier League",
        startTime: new Date(Date.now() + 8 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 10 * 60 * 60 * 1000),
        category: "football",
        status: "upcoming",
        currentScore: null,
        markets: [
          {
            id: "fallback-epl-1-winner",
            name: "Match Winner",
            outcomes: [
              { id: "united-win", name: "Manchester United", odds: 2.4, impliedProbability: 41.7 },
              { id: "liverpool-win", name: "Liverpool", odds: 1.9, impliedProbability: 52.6 },
              { id: "draw", name: "Draw", odds: 3.5, impliedProbability: 28.6 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 1100000,
        participantCount: 1850,
      },
      {
        id: "fallback-epl-2",
        title: "Manchester City vs Arsenal",
        description: "Premier League",
        startTime: new Date(Date.now() + 12 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 14 * 60 * 60 * 1000),
        category: "football",
        status: "upcoming",
        currentScore: null,
        markets: [
          {
            id: "fallback-epl-2-winner",
            name: "Match Winner",
            outcomes: [
              { id: "city-win", name: "Manchester City", odds: 1.7, impliedProbability: 58.8 },
              { id: "arsenal-win", name: "Arsenal", odds: 2.5, impliedProbability: 40.0 },
              { id: "draw", name: "Draw", odds: 3.8, impliedProbability: 26.3 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 1200000,
        participantCount: 2000,
      },
      {
        id: "fallback-epl-3",
        title: "Chelsea vs Tottenham",
        description: "Premier League - London Derby",
        startTime: new Date(Date.now() + 16 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 18 * 60 * 60 * 1000),
        category: "football",
        status: "upcoming",
        currentScore: null,
        markets: [
          {
            id: "fallback-epl-3-winner",
            name: "Match Winner",
            outcomes: [
              { id: "chelsea-win", name: "Chelsea", odds: 2.0, impliedProbability: 50.0 },
              { id: "spurs-win", name: "Tottenham", odds: 2.2, impliedProbability: 45.5 },
              { id: "draw", name: "Draw", odds: 3.4, impliedProbability: 29.4 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 850000,
        participantCount: 1650,
      },
      {
        id: "fallback-bundesliga-1",
        title: "Bayern Munich vs Borussia Dortmund",
        description: "Bundesliga - Der Klassiker",
        startTime: new Date(Date.now() + 20 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 22 * 60 * 60 * 1000),
        category: "football",
        status: "upcoming",
        currentScore: null,
        markets: [
          {
            id: "fallback-bundesliga-1-winner",
            name: "Match Winner",
            outcomes: [
              { id: "bayern-win", name: "Bayern Munich", odds: 1.8, impliedProbability: 55.6 },
              { id: "dortmund-win", name: "Borussia Dortmund", odds: 2.4, impliedProbability: 41.7 },
              { id: "draw", name: "Draw", odds: 3.6, impliedProbability: 27.8 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 780000,
        participantCount: 1400,
      },
      // Basketball Events (15 events)
      {
        id: "fallback-nba-1",
        title: "Los Angeles Lakers vs Boston Celtics",
        description: "NBA Regular Season",
        startTime: new Date(Date.now() + 6 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 9 * 60 * 60 * 1000),
        category: "basketball",
        status: "upcoming",
        currentScore: null,
        markets: [
          {
            id: "fallback-nba-1-winner",
            name: "Match Winner",
            outcomes: [
              { id: "lakers-win", name: "Los Angeles Lakers", odds: 1.95, impliedProbability: 51.3 },
              { id: "celtics-win", name: "Boston Celtics", odds: 1.85, impliedProbability: 54.1 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 580000,
        participantCount: 1200,
      },
      {
        id: "fallback-nba-2",
        title: "Golden State Warriors vs Phoenix Suns",
        description: "NBA Regular Season",
        startTime: new Date(Date.now() + 12 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 15 * 60 * 60 * 1000),
        category: "basketball",
        status: "upcoming",
        currentScore: null,
        markets: [
          {
            id: "fallback-nba-2-winner",
            name: "Match Winner",
            outcomes: [
              { id: "warriors-win", name: "Golden State Warriors", odds: 2.1, impliedProbability: 47.6 },
              { id: "suns-win", name: "Phoenix Suns", odds: 1.75, impliedProbability: 57.1 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 420000,
        participantCount: 890,
      },
      {
        id: "fallback-nba-3",
        title: "Miami Heat vs Milwaukee Bucks",
        description: "NBA Eastern Conference",
        startTime: new Date(Date.now() + 18 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 21 * 60 * 60 * 1000),
        category: "basketball",
        status: "upcoming",
        currentScore: null,
        markets: [
          {
            id: "fallback-nba-3-winner",
            name: "Match Winner",
            outcomes: [
              { id: "heat-win", name: "Miami Heat", odds: 2.3, impliedProbability: 43.5 },
              { id: "bucks-win", name: "Milwaukee Bucks", odds: 1.65, impliedProbability: 60.6 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 520000,
        participantCount: 950,
      },
      // Live Events (5 events)
      {
        id: "fallback-live-1",
        title: "Chelsea vs Arsenal",
        description: "Premier League - Live",
        startTime: new Date(Date.now() - 30 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 60 * 60 * 1000),
        category: "football",
        status: "live",
        currentScore: "1-1",
        markets: [
          {
            id: "fallback-live-1-winner",
            name: "Match Winner",
            outcomes: [
              { id: "chelsea-win", name: "Chelsea", odds: 2.2, impliedProbability: 45.5 },
              { id: "arsenal-win", name: "Arsenal", odds: 2.0, impliedProbability: 50.0 },
              { id: "draw", name: "Draw", odds: 3.8, impliedProbability: 26.3 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 890000,
        participantCount: 1650,
      },
      {
        id: "fallback-live-2",
        title: "Denver Nuggets vs Los Angeles Clippers",
        description: "NBA - Live",
        startTime: new Date(Date.now() - 45 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 75 * 60 * 60 * 1000),
        category: "basketball",
        status: "live",
        currentScore: "78-82",
        markets: [
          {
            id: "fallback-live-2-winner",
            name: "Match Winner",
            outcomes: [
              { id: "nuggets-win", name: "Denver Nuggets", odds: 1.9, impliedProbability: 52.6 },
              { id: "clippers-win", name: "Los Angeles Clippers", odds: 1.9, impliedProbability: 52.6 },
            ],
            isResolved: false,
          },
        ],
        totalVolume: 650000,
        participantCount: 1100,
      },
    ];